### ISSUE TITLE
Mazda 3 BM not working, device not responding

### ISSUE THREAD

**Issue by sacredneobi** [nisargjhaveri/WirelessAndroidAutoDongle#87]
Raspberry Pi zero w 2, load from pre-build image after connect phone show Android auto available, connect success and show continue on Head unit but on car show USB 1 not responding

**Comment by nisargjhaveri** [comment]
If you can get some logs, it might help. Also, you can try connecting with wire once and then using the dongle and see if that helps?

**Comment by sacredneobi** [comment]
Yesterday I tried to connect after the cable but nothing worked. But today I connected to get the logs and everything worked fine right away. But in the beginning it always continues to write USB1 the device does not respond, I understand that at the moment of loading OTG will be transferred to the Dongle state but does not yet have a signature or ID. I couldn’t get the logs because the file contains a lot of information about the data transfer. You can add the nano test editor to the repository. I send log late with out connect phone I want to check the work as a whole now

**Comment by nisargjhaveri** [comment]
With b58cc9d9bfc83215549438a7f0cec10b97bf920b, the verbosity of the logs should be reduced a lot.

**Comment by nisargjhaveri** [comment]
@sacredneobi were you able to resolve the original issue? If not, you can try the latest version and share the logs if it still doesn't work?

**Comment by NabeelUppel** [comment]
I have the same issue that happens randomly. (Also Mazda 3) I'm using the latest version. 

So on Mazdas, it connects automatically to the last connected device, in this case being the USB port.

What I suspect is happening that's it's trying to connect while the Pi is still being start up and initilaized and that throws "the USB device not responding" error. 

I wonder if there's a way to add a delay to the USB port OTG capabilities, so that the Pi boots up with the car but the car won't recognise any USB device until the delay is over. (Maybe as a env variable so it's customisable, so those who don't need it can use the default value of 0.)

**Comment by nisargjhaveri** [comment]
Looks like this might've been solved from the comments on the linked PR. Closing for now. Feel free to reopen as needed.
